### ISSUE TITLE
AdGuard certificate

### ISSUE THREAD

**Issue by innit86** [fany0r/MoveUserCertificate#1]
Hi. Could you add support for AdGuard certificate? Their module doesn't work on the latest Magisk Canary 26.4 (26404) (65207f96) (CANARY) and they don't react to bug reports.

https://github.com/AdguardTeam/adguardcert

**Comment by fany0r** [comment]
In reality, the module doesn't differentiate between individual app certificates. After installation, it automatically copies the all user-level certificate to the system area upon each device reboot.
