### ISSUE TITLE
大佬你好，kernelSU 上能用吗

### ISSUE THREAD

**Issue by TensorFu** [fany0r/MoveUserCertificate#2]
大佬你好，kernelSU 上能用吗

**Comment by fany0r** [comment]
没用过kernelSU，不清楚适用与否。
但，所有的操作都是执行`service.sh`完成的，和[kernelSU](https://kernelsu.org/zh_CN/guide/difference-with-magisk.html)的一样，或许能用。

**Comment by TensorFu** [comment]
> 没用过kernelSU，不清楚适用与否。 但，所有的操作都是执行`service.sh`完成的，和[kernelSU](https://kernelsu.org/zh_CN/guide/difference-with-magisk.html)的一样，或许能用。

是的，我已经找到了关键的部分，现在我一直都是手动执行的，KernelSU 好像不支持这个模块
